# For more info on HTTP files go to https://aka.ms/vs/httpfile
GET https://api.openrouteservice.org/geocode/search?api_key=5b3ce3597851110001cf6248df48d3575b00fdc1243d5733eeba4c301abc9f15d8b8e562f38e1a09&text=fh%20technikum