using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Security.Cryptography.X509Certificates;
using System.Windows.Markup;

namespace TourPlannerClasses.Models
{
    public class TourList
    {
        public List<Tours> AllTours { get; set; }
        public TourList() { }
    }

    public class Tours
    {
        
        [Key]   //primary key
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]   //autogenerated
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string From { get; set; }
        public double FromLat { get; set; }
        public double FromLng { get; set; }
        public string To { get; set; }
        public double ToLat { get; set; }
        public double ToLng { get; set; }
        public TimeSpan Duration { get; set; }
        public double Distance { get; set; }
        public TransportType Transport { get; set; }

        public virtual ICollection<Tourlog> Tourlogs { get; set; } = new List<Tourlog>();
        
        [NotMapped]
        public int Popularity => Tourlogs?.Count ?? 0;
        [NotMapped]
        public bool IsChildFriendly
        {
            get
            {
                if (Tourlogs == null || !Tourlogs.Any())
                    return false;

                var avgDifficulty = Tourlogs.Average(tl => (int)tl.Difficulty);
                var avgDistance = Tourlogs.Average(tl => tl.TotalDistance);
                var avgDuration = Tourlogs.Average(tl => tl.TotalTime.TotalHours);

                return avgDifficulty <= (int)Difficulty.Medium
                    && avgDistance <= 10
                    && avgDuration <= 2;
            }
        }

        public Tours() { }

        public Tours(int id, string name, string description, string from, double fromLat, double fromLng, string to, double toLat, double toLng, TimeSpan duration, double distance, TransportType transport)
        {
            this.Id = id;
            this.Name = name;
            this.Description = description;
            this.From = from;
            this.FromLat = fromLat;
            this.FromLng = fromLng;
            this.To = to;
            this.ToLat = toLat;
            this.ToLng = toLng;
            this.Duration = duration;
            this.Distance = distance;
            this.Transport = transport;
        }
    }

    public enum TransportType
    {
        Walking,    //0
        Bicycle,    //1
        Car,        //2
    }
}
