using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Security.Cryptography.X509Certificates;
using System.Windows.Markup;

namespace TourPlannerClasses.Models
{
    public class TourList
    {
        public List<Tours> AllTours { get; set; }
        public TourList() { }
    }

    public class Tours
    {
        
        [Key]   //primary key
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]   //autogenerated
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public TimeSpan Duration { get; set; }
        public double Distance { get; set; }
        public TransportType Transport { get; set; }

        public virtual ICollection<Tourlog> Tourlogs { get; set; } = new List<Tourlog>();

        public Tours() { }

        public Tours(int id, string name, string description, string from, string to, TimeSpan duration, double distance, TransportType transport)
        {
            this.Id = id;
            this.Name = name;
            this.Description = description;
            this.From = from;
            this.To = to;
            this.Duration = duration;
            this.Distance = distance;
            this.Transport = transport;
        }
    }

    public enum TransportType
    {
        Walking,    //0
        Bicycle,    //1
        Tram,       //2
        Bus,        //3
        Train,      //4
        Car,        //5
        Plane,      //6
        Boat        //7
    }
}
